/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alterar-senha`; params?: Router.UnknownInputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/criar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/detalhes-evento`; params?: Router.UnknownInputParams; } | { pathname: `/detalhes-lojista`; params?: Router.UnknownInputParams; } | { pathname: `/editar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/editar-perfil`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mapa-selecao`; params?: Router.UnknownInputParams; } | { pathname: `/privacidade`; params?: Router.UnknownInputParams; } | { pathname: `/resetar-senha`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/termos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/meus-eventos` | `/meus-eventos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/components/FiltroModal`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/alterar-senha`; params?: Router.UnknownOutputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownOutputParams; } | { pathname: `/criar-evento`; params?: Router.UnknownOutputParams; } | { pathname: `/detalhes-evento`; params?: Router.UnknownOutputParams; } | { pathname: `/detalhes-lojista`; params?: Router.UnknownOutputParams; } | { pathname: `/editar-evento`; params?: Router.UnknownOutputParams; } | { pathname: `/editar-perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/mapa-selecao`; params?: Router.UnknownOutputParams; } | { pathname: `/privacidade`; params?: Router.UnknownOutputParams; } | { pathname: `/resetar-senha`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/sobre`; params?: Router.UnknownOutputParams; } | { pathname: `/termos`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/meus-eventos` | `/meus-eventos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/components/FiltroModal`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/alterar-senha${`?${string}` | `#${string}` | ''}` | `/configuracoes${`?${string}` | `#${string}` | ''}` | `/criar-evento${`?${string}` | `#${string}` | ''}` | `/detalhes-evento${`?${string}` | `#${string}` | ''}` | `/detalhes-lojista${`?${string}` | `#${string}` | ''}` | `/editar-evento${`?${string}` | `#${string}` | ''}` | `/editar-perfil${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/mapa-selecao${`?${string}` | `#${string}` | ''}` | `/privacidade${`?${string}` | `#${string}` | ''}` | `/resetar-senha${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | `/termos${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favoritos${`?${string}` | `#${string}` | ''}` | `/favoritos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/meus-eventos${`?${string}` | `#${string}` | ''}` | `/meus-eventos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `/components/FiltroModal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/alterar-senha`; params?: Router.UnknownInputParams; } | { pathname: `/configuracoes`; params?: Router.UnknownInputParams; } | { pathname: `/criar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/detalhes-evento`; params?: Router.UnknownInputParams; } | { pathname: `/detalhes-lojista`; params?: Router.UnknownInputParams; } | { pathname: `/editar-evento`; params?: Router.UnknownInputParams; } | { pathname: `/editar-perfil`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mapa-selecao`; params?: Router.UnknownInputParams; } | { pathname: `/privacidade`; params?: Router.UnknownInputParams; } | { pathname: `/resetar-senha`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/termos`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favoritos` | `/favoritos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/meus-eventos` | `/meus-eventos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/components/FiltroModal`; params?: Router.UnknownInputParams; };
    }
  }
}
